**Small example on KNN-mathmatics, iris-dataset**

In [137]:
# usual imports
import numpy as np
import pandas as pd
import seaborn as sns

In [138]:
# load the iris dataset
df = sns.load_dataset("iris")

In [139]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [140]:
# 50 of each flower type: setosa, versicolor and virginica
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [141]:
# we are going to only use sepal width and sepal length for our math demonstration
df = df[['sepal_length', 'sepal_width', 'species']]

In [142]:
df

     sepal_length  sepal_width    species
0             5.1          3.5     setosa
1             4.9          3.0     setosa
2             4.7          3.2     setosa
3             4.6          3.1     setosa
4             5.0          3.6     setosa
..            ...          ...        ...
145           6.7          3.0  virginica
146           6.3          2.5  virginica
147           6.5          3.0  virginica
148           6.2          3.4  virginica
149           5.9          3.0  virginica

[150 rows x 3 columns]

In [143]:
# new data from user (or something similar)
sl_new = 7.1
sw_new = 3.6

# so what is the species for this flower with these measurements?
# => most probable species based on these values

In [144]:
# calculate the Euclidean distance with the current dataset and new values
# above, original formula is in the materials
df['distance'] = np.sqrt((sl_new - df['sepal_length']) ** 2 + (sw_new - df['sepal_width']) ** 2)

C:\Users\tuomas.valtanen\AppData\Local\Temp\ipykernel_15896\3623456673.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['distance'] = np.sqrt((sl_new - df['sepal_length']) ** 2 + (sw_new - df['sepal_width']) ** 2)

In [145]:
df

     sepal_length  sepal_width    species  distance
0             5.1          3.5     setosa  2.002498
1             4.9          3.0     setosa  2.280351
2             4.7          3.2     setosa  2.433105
3             4.6          3.1     setosa  2.549510
4             5.0          3.6     setosa  2.100000
..            ...          ...        ...       ...
145           6.7          3.0  virginica  0.721110
146           6.3          2.5  virginica  1.360147
147           6.5          3.0  virginica  0.848528
148           6.2          3.4  virginica  0.921954
149           5.9          3.0  virginica  1.341641

[150 rows x 4 columns]

In [ ]:
# sort the data based on distance
# based on distance, assign each training data flower a rank
# closest neighbor => 1, furthest neighbor => highest rank
df = df.sort_values("distance", ascending=True)
df = df.reset_index()
df = df.drop("index", axis=1)
df['rank'] = df.index + 1
df

     sepal_length  sepal_width     species  distance  rank
0             7.2          3.6   virginica  0.100000     1
1             7.0          3.2  versicolor  0.412311     2
2             7.2          3.2   virginica  0.412311     3
3             6.9          3.2   virginica  0.447214     4
4             6.7          3.3   virginica  0.500000     5
..            ...          ...         ...       ...   ...
145           4.4          3.2      setosa  2.729469   146
146           4.4          3.0      setosa  2.765863   147
147           4.4          2.9      setosa  2.789265   148
148           4.3          3.0      setosa  2.863564   149
149           4.5          2.3      setosa  2.906888   150

[150 rows x 5 columns]

In [ ]:
# k-value => how many nearest neighboring rows 
# we want to take into account
# when we make our decision of the output
k_value = 10

# just show the relevant rows based on our k-value
sample = df[df['rank'] <= k_value]
sample

   sepal_length  sepal_width     species  distance  rank
0           7.2          3.6   virginica  0.100000     1
1           7.0          3.2  versicolor  0.412311     2
2           7.2          3.2   virginica  0.412311     3
3           6.9          3.2   virginica  0.447214     4
4           6.7          3.3   virginica  0.500000     5
5           6.7          3.3   virginica  0.500000     6
6           6.8          3.2   virginica  0.500000     7
7           6.9          3.1  versicolor  0.538516     8
8           6.9          3.1   virginica  0.538516     9
9           6.9          3.1   virginica  0.538516    10